### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by remram44** [JosuaKrause/info#1]
If you rename this repository "josuakrause.github.io", it will be available at that URL instead of `http://josuakrause.github.io/info/`

https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages

**Comment by JosuaKrause** [comment]
I added a [redirect from the user page](https://github.com/JosuaKrause/josuakrause.github.io/commit/abc3311d73c9fea6ca7ff26b8a038620a3292818).
